# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "passenger_monit"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Shterenzon"]
  s.date = "2013-02-22"
  s.description = "Support for monitoring Passenger with Monit"
  s.email = "romanbsd@yahoo.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/passenger_monit.rb",
    "lib/passenger_monit/pidfile_manager.rb",
    "passenger_monit.gemspec",
    "test/passenger_monit_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/romanbsd/passenger_monit"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Support for monitoring Passenger with Monit"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

